CREATE TABLE GYMNASTIS(
     ID_GYM  INT  NOT NULL,
     ONOMA CHARACTER(20) NOT NULL,
     EPITHETO CHARACTER(20),
     EMAIL CHARACTER(30) NULL,
     PHONE INT NOT NULL,
     USERNAME CHARACTER(20) NOT NULL,
     PASSWORD CHARACTER(30) NOT NULL
) 

CREATE TABLE OMADIKA_PROGRAMMATA (AR_PROGRAMMATOS INT NOT NULL, MERA DATE NOT NULL, ORA TIME NOT NULL, ONOMA_PROGRAMMATOS CHARACTER(30) NOT NULL, AR_THESEON INT NOT NULL, ID_GYM INT NOT NULL)

CREATE TABLE  PROGRAMMA (
    ID_GYM INT  NOT NULL,
     AR_PROGRAMMATOS INT NOT NULL,
     PERIEXOMENO IMAGE  NOT NULL,
     TITLOS CHARACTER(30) NOT NULL,
     DIARKEIA INT NOT NULL,
     TUPOS  CHARACTER(20)
) 

CREATE TABLE PELATIS(
    ID_GYM INT  NOT NULL,
    AR_PROGRAMMATOS INT  NOT NULL,
     ID_NUM  INT NOT NULL,
     ONOMA CHARACTER(20) NOT NULL,
     EPITHETO CHARACTER(20),
     PHONE INT  NOT NULL,
     IM_GENNISIS  DATE NOT NULL,
     DIEUTHINSI CHARACTER(50) NOT NULL,
     FULO  CHARACTER(1) NOT NULL,
     EMAIL  CHARACTER(20) NULL,
     START_DATE  DATE  NOT NULL,
     USERNAME CHARACTER (30) NOT NULL,
     PASSWORD CHARACTER (30) NOT NULL,
     AR_PAKETOU INT NOT NULL,
     PACKET_END_DATE  DATE  NOT NULL
)

 CREATE TABLE PAKETO_SUNDROMIS(
    AR_PAKETOU INT NOT NULL,
    TIMI INT  NOT NULL,
    DIARKEIA  INT  NOT NULL
) 
CREATE TABLE APODIKSI (
    AR_UPIRESIAS INT NOT NULL,
    ID_PELATI INT  NOT NULL,
    AR_APODIKSIS INT ,
    POSO INT NOT NULL,
     IMEROMINIA DATE  NOT NULL,
     ORA TIME NOT NULL
)
 CREATE TABLE PHYSIOTHERAPIA(
     AR_RANTEVOU INT NOT NULL,
     MERA  DATE  NOT NULL,
     ORA  TIME  NOT NULL,
     PERIGRAFI CHARACTER (50) NULL,
     ID_PHYSIO   INT  NOT NULL,
    ID_PELATI INT NOT NULL
) 
CREATE TABLE PHYSIOTHERAPEUTIS(
    ID_PHYSIO INT  NOT NULL,
     ONOMA CHARACTER(20) NOT NULL,
     EPITHETO CHARACTER(20) NOT NULL,
     EMAIL  CHARACTER(50) NULL,
     PHONE INT  NOT NULL,
    USERNAME  CHARACTER(20),
     PASSWORD CHARACTER(30) NOT NULL
)
CREATE TABLE SERVICES (
     AR_UPIRESIAS INT  NOT NULL,
     TYPOS CHARACTER(20) NOT NULL
)
 CREATE TABLE KRATISIS (
    AR_UPIRESIAS INT NOT NULL,
     ID_PELATI INT  NOT NULL,
     MERA  DATE  NOT NULL,
     ORA TIME  NOT NULL
) 
CREATE TABLE EGGRAFES_PROGRAMMATA (
     ID_PELATI INT  NOT NULL,
     AR_PROGRAMMATOS INT  NOT NULL
) 

ALTER TABLE   GYMNASTIS  ADD CONSTRAINT PK_GYMNASTI PRIMARY KEY( ID_GYM )
ALTER TABLE OMADIKA_PROGRAMMATA ADD CONSTRAINT PK_OMADIKA_PROGRAMMATA PRIMARY KEY(AR_PROGRAMMATOS)
ALTER TABLE PROGRAMMA  ADD CONSTRAINT PK_PROGRAMMA PRIMARY KEY(ID_GYM, AR_PROGRAMMATOS )
ALTER TABLE PAKETO_SUNDROMIS  ADD CONSTRAINT PK_PAKETOU_SUNDROMIS PRIMARY KEY(AR_PAKETOU)
ALTER TABLE PELATIS   ADD CONSTRAINT PK_PELATIS PRIMARY KEY(ID_NUM)
ALTER TABLE APODIKSI  ADD CONSTRAINT PK_APODIKSIS PRIMARY KEY(AR_APODIKSIS)
ALTER TABLE PHYSIOTHERAPIA  ADD CONSTRAINT PK_PHYSIOTHERAPIAS PRIMARY KEY(AR_RANTEVOU)
ALTER TABLE PHYSIOTHERAPEUTIS  ADD CONSTRAINT PRIMARY KEY( ID_PHYSIO )
ALTER TABLE SERVICES  ADD CONSTRAINT PK_SERVICES PRIMARY KEY(AR_UPIRESIAS)
ALTER TABLE KRATISIS  ADD CONSTRAINT PK_KRATISIS PRIMARY KEY( AR_UPIRESIAS,ID_PELATI,MERA,ORA)
ALTER TABLE EGGRAFES_PROGRAMMATA ADD CONSTRAINT PK_EGGRAFES PRIMARY KEY(ID_PELATI, AR_PROGRAMMATOS )
ALTER TABLE EGGRAFES_PROGRAMMATA ADD CONSTRAINT FK_EGGRAFES FOREIGN KEY(ID_PELATI) REFERENCES PELATIS( ID_NUM )
ALTER TABLE EGGRAFES_PROGRAMMATA  ADD CONSTRAINT FK_EGGRAFES1 FOREIGN KEY(AR_PROGRAMMATOS) REFERENCES OMADIKA_PROGRAMMATA (AR_PROGRAMMATOS)
ALTER TABLE APODIKSI  ADD CONSTRAINT FK_APODIKSIS FOREIGN KEY(ID_PELATI) REFERENCES PELATIS (ID_NUM)
ALTER TABLE PHYSIOTHERAPIA  ADD CONSTRAINT FK_PHYSIO FOREIGN KEY(ID_PHYSIO) REFERENCES PHYSIOTHERAPEUTIS (ID_PHYSIO)
ALTER TABLE PHYSIOTHERAPIA  ADD CONSTRAINT FK_PHYSIO1 FOREIGN KEY(ID_PELATI) REFERENCES PELATIS( ID_NUM )
ALTER TABLE KRATISIS  ADD CONSTRAINT FK_KRATISIS FOREIGN KEY(AR_UPIRESIAS) REFERENCES SERVICES ( AR_UPIRESIAS )
ALTER TABLE KRATISIS  ADD CONSTRAINT FK_KRATISIS1 FOREIGN KEY(ID_PELATI) REFERENCES PELATIS ( ID_NUM )
ALTER TABLE OMADIKA_PROGRAMMATA   ADD CONSTRAINT  FK_OMADIKA_PROGRAMMATA FOREIGN KEY ( ID_GYM ) REFERENCES GYMNASTIS ( ID_GYM )
ALTER TABLE PROGRAMMA  ADD CONSTRAINT FK_PROGRAMMA FOREIGN KEY( ID_GYM ) REFERENCES GYMNASTIS ( ID_GYM )
ALTER TABLE PELATIS  ADD CONSTRAINT FK_PELATIS FOREIGN KEY( ID_GYM ,  AR_PROGRAMMATOS ) REFERENCES  PROGRAMMA ( ID_GYM ,  AR_PROGRAMMATOS )
ALTER TABLE PELATIS  ADD CONSTRAINT FK_PELATIS1  FOREIGN KEY( AR_PAKETOU ) REFERENCES PAKETO_SUNDROMIS ( AR_PAKETOU )